# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'capybara_tw/gui/preferences_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName("PreferencesDialog")
        PreferencesDialog.resize(520, 550)
        self.gridLayout = QtWidgets.QGridLayout(PreferencesDialog)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(PreferencesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(PreferencesDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.appearanceTab = QtWidgets.QWidget()
        self.appearanceTab.setObjectName("appearanceTab")
        self.tuGridGroupBox = QtWidgets.QGroupBox(self.appearanceTab)
        self.tuGridGroupBox.setGeometry(QtCore.QRect(30, 20, 441, 91))
        self.tuGridGroupBox.setObjectName("tuGridGroupBox")
        self.widget = QtWidgets.QWidget(self.tuGridGroupBox)
        self.widget.setGeometry(QtCore.QRect(30, 40, 105, 23))
        self.widget.setObjectName("widget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.tuGridFontSizeLabel = QtWidgets.QLabel(self.widget)
        self.tuGridFontSizeLabel.setObjectName("tuGridFontSizeLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tuGridFontSizeLabel)
        self.tuGridFontSizeSpinBox = QtWidgets.QSpinBox(self.widget)
        self.tuGridFontSizeSpinBox.setMinimum(10)
        self.tuGridFontSizeSpinBox.setMaximum(30)
        self.tuGridFontSizeSpinBox.setObjectName("tuGridFontSizeSpinBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tuGridFontSizeSpinBox)
        self.editorGroupBox = QtWidgets.QGroupBox(self.appearanceTab)
        self.editorGroupBox.setGeometry(QtCore.QRect(30, 150, 441, 91))
        self.editorGroupBox.setObjectName("editorGroupBox")
        self.widget1 = QtWidgets.QWidget(self.editorGroupBox)
        self.widget1.setGeometry(QtCore.QRect(30, 40, 105, 23))
        self.widget1.setObjectName("widget1")
        self.formLayout_3 = QtWidgets.QFormLayout(self.widget1)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.editorsFontSizeLabel = QtWidgets.QLabel(self.widget1)
        self.editorsFontSizeLabel.setObjectName("editorsFontSizeLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.editorsFontSizeLabel)
        self.editorsFontSizeSpinBox = QtWidgets.QSpinBox(self.widget1)
        self.editorsFontSizeSpinBox.setMinimum(10)
        self.editorsFontSizeSpinBox.setMaximum(30)
        self.editorsFontSizeSpinBox.setObjectName("editorsFontSizeSpinBox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editorsFontSizeSpinBox)
        self.tabWidget.addTab(self.appearanceTab, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 1, 1, 1)

        self.retranslateUi(PreferencesDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(PreferencesDialog.accept)
        self.buttonBox.rejected.connect(PreferencesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)

    def retranslateUi(self, PreferencesDialog):
        _translate = QtCore.QCoreApplication.translate
        PreferencesDialog.setWindowTitle(_translate("PreferencesDialog", "Preferences"))
        self.tuGridGroupBox.setTitle(_translate("PreferencesDialog", "Translation grid"))
        self.tuGridFontSizeLabel.setText(_translate("PreferencesDialog", "Font size:"))
        self.editorGroupBox.setTitle(_translate("PreferencesDialog", "Editors"))
        self.editorsFontSizeLabel.setText(_translate("PreferencesDialog", "Font size:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.appearanceTab), _translate("PreferencesDialog", "Appearance"))
